# __Introducción a Numpy__

#### Semana 1

### __Daniela Díaz Mora__
#### consultas a daniela.diaz@sansano.usm.cl

## _Index_
1. [Array](#id1)
2. [LinAlg](#id2)

In [4]:
import numpy as np ##importar la libreria

<div id='id1' />

### Array

In [7]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

In [9]:
a=np.array([[1,2,3]]) #vector fila
a.shape

(1, 3)

In [11]:
a=np.array([[1],[2],[3]]) #vector columna
a.shape

array([[1],
       [2],
       [3]])

In [31]:
a=np.array([[1,2,3],[3,2,1]]) #arreglo multidimensional
a

array([[1, 2, 3],
       [3, 2, 1]])

In [14]:
# crear una matriz de 1's o 0's

zeros=np.zeros([10,3])
ones=np.ones(3)

In [13]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
ones

array([1., 1., 1.])

In [53]:
#crear una matriz diagonal
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.diag([1,2,4,7,9])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [23]:
#arreglo desde el numero de inicio hasta n-1
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#arreglo equispaciado
np.linspace(1,33,10)

array([ 1.        ,  4.55555556,  8.11111111, 11.66666667, 15.22222222,
       18.77777778, 22.33333333, 25.88888889, 29.44444444, 33.        ])

<div id='id2' />


### Linalg

In [31]:
A= np.ones([5,5])
B= np.arange(1,26).reshape(5,5)
print(A,'\n \n', B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
A+B #suma elemento a elemento

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

In [33]:
A-B #resta

array([[  0.,  -1.,  -2.,  -3.,  -4.],
       [ -5.,  -6.,  -7.,  -8.,  -9.],
       [-10., -11., -12., -13., -14.],
       [-15., -16., -17., -18., -19.],
       [-20., -21., -22., -23., -24.]])

In [79]:
A*B #multiplicación elemento a elemento

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [35]:
A@B==np.dot(A,B) #producto matricial tipico

array([[55., 60., 65., 70., 75.],
       [55., 60., 65., 70., 75.],
       [55., 60., 65., 70., 75.],
       [55., 60., 65., 70., 75.],
       [55., 60., 65., 70., 75.]])

### Descomposición QR

Una matriz $A\in \mathbb{R}_{n\times n}$ puede descomponerse de la siguiente forma

$$ A=QR$$

donde $Q$ es una matriz ortogonal y $R$ es una matriz triangular superior.

In [41]:
#Descomposición QR
Q,R=np.linalg.qr(A)
print('Q=',Q,'\n R=',R)

Q= [[-4.47213595e-01  8.94427191e-01 -4.01682464e-17 -4.01682464e-17
  -8.03364928e-17]
 [-4.47213595e-01 -2.23606798e-01 -5.00000000e-01 -5.00000000e-01
  -5.00000000e-01]
 [-4.47213595e-01 -2.23606798e-01  8.33333333e-01 -1.66666667e-01
  -1.66666667e-01]
 [-4.47213595e-01 -2.23606798e-01 -1.66666667e-01  8.33333333e-01
  -1.66666667e-01]
 [-4.47213595e-01 -2.23606798e-01 -1.66666667e-01 -1.66666667e-01
   8.33333333e-01]] 
 R= [[-2.23606798e+00 -2.23606798e+00 -2.23606798e+00 -2.23606798e+00
  -2.23606798e+00]
 [ 0.00000000e+00 -2.22044605e-16 -2.22044605e-16 -2.22044605e-16
  -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]]


In [42]:
#valores propios y vectores propios
np.linalg.eig(A)[0] #valores propios

array([-4.44089210e-16,  5.00000000e+00,  5.55111512e-17,  6.16297582e-33,
        0.00000000e+00])

In [43]:
np.linalg.eig(A)[1] #vectores propios

array([[-8.94427191e-01, -4.47213595e-01, -2.56494588e-02,
         7.54543047e-17,  6.95533379e-17],
       [ 2.23606798e-01, -4.47213595e-01, -2.82144047e-01,
         3.70074342e-17,  4.02860259e-17],
       [ 2.23606798e-01, -4.47213595e-01, -2.82144047e-01,
        -4.08248290e-01, -7.17429785e-01],
       [ 2.23606798e-01, -4.47213595e-01, -2.82144047e-01,
        -4.08248290e-01,  2.11191610e-02],
       [ 2.23606798e-01, -4.47213595e-01,  8.72081599e-01,
         8.16496581e-01,  6.96310624e-01]])

In [44]:
np.linalg.det(B) #determinante

0.0